### ISSUE TITLE
Missing fastify plugin export on shipped TS types

### ISSUE THREAD

**Issue by fox1t** [piscinajs/fastify-piscina#2]
Trying to register piscinaPlugin in a TS project throws "provides no match for the signature" compiler error. After some digging into types, I found that there is no exported Fastify plugin that is necessary in order to register it.

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/1620916/83003292-6607e080-a00e-11ea-883b-02be89f9a877.png">

If needed, I've already fixed typing and can make a PR.

**Comment by fox1t** [comment]
I opened a PR for further discussion.
https://github.com/piscinajs/fastify-piscina/pull/3

**Comment by jasnell** [comment]
This landed! thank you
